/*
 * 01_skeleton.sql
 * This script sets up the initial database, schemas, and mock data for the dbt_demo project.
 * 
 * Note that the setup of actual dummy tables and data is not strictly necessary for this
 * demo, but included for completeness and for potential future use cases.
 */

-- 1. SET UP ROLES AND WAREHOUSE
USE ROLE SYSADMIN; 
CREATE OR REPLACE WAREHOUSE DEMO_CORTEX_WH WITH WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60;
USE WAREHOUSE DEMO_CORTEX_WH;

-- 2. CREATE DATABASE AND SCHEMAS
CREATE DATABASE IF NOT EXISTS DEMO_CORTEX_DEMO;
CREATE SCHEMA IF NOT EXISTS DEMO_CORTEX_DEMO.DBT_PROJECT; -- Schema for Git Repo and Cortex objects
CREATE SCHEMA IF NOT EXISTS DEMO_CORTEX_DEMO.RAW_DATA; -- Schema for source data
USE SCHEMA DEMO_CORTEX_DEMO.RAW_DATA;

-- 3. MOCK DATA: PATIENTS TABLE
CREATE OR REPLACE TABLE PATIENTS (
    PATIENT_ID VARCHAR,
    DATE_OF_BIRTH DATE,
    INSURANCE_PLAN VARCHAR,
    PCP_ID VARCHAR
);

INSERT INTO PATIENTS (PATIENT_ID, DATE_OF_BIRTH, INSURANCE_PLAN, PCP_ID) VALUES
('P-1001', '1955-03-15', 'MEDICARE ADVANTAGE', 'DR-1'), -- High Risk: Age & Medicare
('P-1002', '1998-11-20', 'BLUE CROSS', 'DR-2'),
('P-1003', '1938-01-01', 'CASH PAY', 'DR-3'), -- High Risk: Age only
('P-1004', '2010-07-25', 'MEDICAID', 'DR-4');

-- 4. MOCK DATA: ENCOUNTERS TABLE
CREATE OR REPLACE TABLE ENCOUNTERS (
    ENCOUNTER_ID VARCHAR,
    PATIENT_ID VARCHAR,
    ENCOUNTER_DATE DATE,
    PROVIDER_ID VARCHAR,
    PRIMARY_DX_CODE VARCHAR, -- Diagnosis Code (ICD-10)
    PLACE_OF_SERVICE VARCHAR
);

INSERT INTO ENCOUNTERS (ENCOUNTER_ID, PATIENT_ID, ENCOUNTER_DATE, PROVIDER_ID, PRIMARY_DX_CODE, PLACE_OF_SERVICE) VALUES
('E-001', 'P-1001', '2025-01-10', 'DR-1', 'I50', 'C3411'), -- Cardio/Respiratory
('E-002', 'P-1002', '2025-01-15', 'DR-2', 'V80', 'R1231'), -- Preventive
('E-003', 'P-1001', '2025-03-01', 'DR-1', 'J45', 'H8766'), -- Cardio/Respiratory (second encounter)
('E-004', 'P-1004', '2025-04-05', 'DR-4', 'E88', 'H8769'), -- Injury/Trauma
('E-005', 'P-1003', '2025-05-20', 'DR-3', 'A01', 'R1231'); -- Other
