
USE ROLE ACCOUNTADMIN;

DROP DATABASE IF EXISTS DEMO_CORTEX_DEMO;

DROP WAREHOUSE IF EXISTS DEMO_CORTEX_WH;

DROP API INTEGRATION IF EXISTS demo_git_api_integration;

DROP AGENT IF EXISTS snowflake_intelligence.agents.demo_dbt_rag_agent;